In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data_path = '~/intro_to_machine_learning/VGsales'

In [3]:
vgsales = pd.read_csv(data_path+ '/vgsales.csv')

In [4]:
vgsales.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [5]:
vgsales.dtypes

Rank              int64
Name             object
Platform         object
Year            float64
Genre            object
Publisher        object
NA_Sales        float64
EU_Sales        float64
JP_Sales        float64
Other_Sales     float64
Global_Sales    float64
dtype: object

In [9]:
#PIVOT TABLES
vg_platform_totals = vgsales.groupby(['Platform', 'Genre']) # Using multiple fields to group by
vg_totals = vg_platform_totals.sum()
vg_totals.head(20)

                        Rank      Year  NA_Sales  EU_Sales  JP_Sales  \
Platform Genre
2600     Action       303231  109013.0     27.39      1.64      0.00
         Adventure      6297    1983.0      1.59      0.10      0.00
         Fighting       6824    1980.0      1.16      0.07      0.00
         Misc          19364    9902.0      3.34      0.20      0.00
         Platform      16723   17836.0     12.38      0.72      0.00
         Puzzle        41827   15865.0     13.68      0.86      0.00
         Racing        28986    7929.0      2.74      0.16      0.00
         Shooter       72992   43611.0     24.68      1.51      0.00
         Simulation     4348    1981.0      0.42      0.02      0.00
         Sports        85073   19828.0      3.22      0.19      0.00
3DO      Adventure     12637    1995.0      0.00      0.00      0.06
         Puzzle        14999    1994.0      0.00      0.00      0.02
         Simulation    15482    1995.0      0.00      0.00      0.02
3DS      Action      1765709  362389.0     19.49     12.53     22.05
         Adventure    423725   72486.0      1.10      0.80      2.74
         Fighting     123828   28179.0      4.43      2.20      3.19
         Misc         527841  106691.0      2.56      2.13      5.38
         Platform     201287   56358.0     13.19     10.35      6.45
         Puzzle       193005   40253.0      1.29      2.12      1.80
         Racing        79321   20111.0      6.06      4.58      2.81

                     Other_Sales  Global_Sales
Platform Genre
2600     Action             0.22         29.34
         Adventure          0.01          1.70
         Fighting           0.01          1.24
         Misc               0.03          3.58
         Platform           0.16         13.27
         Puzzle             0.15         14.68
         Racing             0.01          2.91
         Shooter            0.28         26.48
         Simulation         0.00          0.45
         Sports             0.04          3.43
3DO      Adventure          0.00          0.06
         Puzzle             0.00          0.02
         Simulation         0.00          0.02
3DS      Action             2.84         57.02
         Adventure          0.18          4.81
         Fighting           0.62         10.46
         Misc               0.40         10.48
         Platform           2.26         32.23
         Puzzle             0.35          5.57
         Racing             1.06         14.49